INT-102: add error mapping
valitydev/adapter-common-lib pull request #20
Opened 2022-04-20 08:07 UTC by karleowne

2022-04-20 08:10 UTC, karleowne commented on src/main/java/dev/vality/adapter/common/mapper/ErrorMapping.java
> +    private static Error getDefaultError() {
![image](https://user-images.githubusercontent.com/19729841/164181951-cd7cbeb1-2354-40f9-aac3-5201db6a8aef.png)

2022-04-20 09:04 UTC, ex01tus requested changes

2022-04-20 09:04 UTC, ex01tus commented on src/main/java/dev/vality/adapter/common/mapper/ErrorMapping.java
> +                    String.format("Unexpected error %s, code = %s, description = %s", error, code, description));
И этот кусок, соответственно, не понадобится.

2022-04-20 14:54 UTC, ex01tus requested changes

2022-04-20 14:54 UTC, ex01tus commented on src/main/java/dev/vality/adapter/common/mapper/ErrorMapping.java
> +                            errorDefinition);
Чет мне кажется, здесь произойдет не то, что задумано. Должно быть `return new WRuntimeException()`.

Ну и раз такое дело, давай еще пару тестов набросаем на этот класс, для уверенности.

2022-04-20 14:54 UTC, ex01tus commented on src/main/java/dev/vality/adapter/common/mapper/ErrorMapping.java
> +        return StringUtils.equals(str1, str2);
Я попутал логику, сорян. Можно было и не трогать ничего :D

2022-04-21 08:19 UTC, ex01tus approved these changes

2022-04-21 08:19 UTC, merged