OPS-226: interface for secrets
valitydev/adapter-common-lib pull request #39
Opened 2022-11-01 15:27 UTC by inallyoung

Так выглядят пути(терминалы/опции) в vault 
<img width="508" alt="Снимок экрана 2022-11-01 в 18 23 23" src="https://user-images.githubusercontent.com/22119973/199271285-82bdd613-94dd-4543-a37f-46d3f5ebee20.png">

А так конкретные секреты по указанному пути
<img width="610" alt="Снимок экрана 2022-11-01 в 18 23 36" src="https://user-images.githubusercontent.com/22119973/199271309-d1d3f1b8-07ba-40b3-9c80-7d90c09d156d.png">

2022-11-01 16:25 UTC, ex01tus requested changes

2022-11-01 16:25 UTC, ex01tus commented on src/main/java/dev/vality/adapter/common/secret/SecretRef.java
> +    private String optionsId;
Если для этой штуки уже есть свой термин – path – то я бы предложил его и использовать. Потому что, например, в новой adapter-flow-lib от термина options уже отходят в пользу adapterConfigurations.

2022-11-01 17:06 UTC, inallyoung commented on src/main/java/dev/vality/adapter/common/exception/NotFoundException.java
> +public class NotFoundException extends Exception {
Использую его в случае если path не найден или если секрет не найден, поэтому назвал так обобщенно. Но наверное создам два разных исключения, логично.

2022-11-01 17:16 UTC, inallyoung commented on src/main/java/dev/vality/adapter/common/secret/SecretService.java
> +    String OPTIONS_ID = "OPTIONS_ID";
Убрал пока что. Верну в реализации, где упоминание vault будет более корректно.

2022-11-01 17:17 UTC, inallyoung commented on src/main/java/dev/vality/adapter/common/secret/SecretService.java
> +     * @throws NotFoundException если ключ не найден
Пофиксил, там всюду должно быть секрет. 
Кроме key в SecretRef, там это ключ секрета в vault

2022-11-01 17:30 UTC, ex01tus approved these changes

2022-11-02 07:47 UTC, strug commented
> Так выглядят пути(терминалы/опции) в vault <img alt="Снимок экрана 2022-11-01 в 18 23 23" width="508" src="https://user-images.githubusercontent.com/22119973/199271285-82bdd613-94dd-4543-a37f-46d3f5ebee20.png">
> 
> А так конкретные секреты по указанному пути <img alt="Снимок экрана 2022-11-01 в 18 23 36" width="610" src="https://user-images.githubusercontent.com/22119973/199271309-d1d3f1b8-07ba-40b3-9c80-7d90c09d156d.png">

а почему passworf - опечатка или не дает создать (не токсичности ради)?

2022-11-02 07:55 UTC, strug commented on src/main/java/dev/vality/adapter/common/exception/SecretPathNotFoundException.java
> +public class SecretPathNotFoundException extends Exception {
А почему не RuntimeException?

2022-11-02 07:55 UTC, strug commented on src/main/java/dev/vality/adapter/common/secret/SecretValue.java
> +public class SecretValue {
А этот бин нужен для возможной сложной структуры в дальнейшем? Типо там можно хранить что-то составное не просто строку? (для моего общего развития)

2022-11-02 09:59 UTC, inallyoung commented on src/main/java/dev/vality/adapter/common/secret/SecretValue.java
> +public class SecretValue {
сделал так, чтоб случайно никто не залогировал value.
А так в vault можно хранить сложные объекты, он их сериализует в json. Но нам это не нужно в рамках kv- секретов.

2022-11-02 10:00 UTC, inallyoung commented on src/main/java/dev/vality/adapter/common/exception/SecretPathNotFoundException.java
> +public class SecretPathNotFoundException extends Exception {
Ну я в олдскульном стиле указал это в throws интерфейса. Типа явно ошибочная ситуация и нужно ее обработать отдельно.

2022-11-02 10:06 UTC, inallyoung commented on src/main/java/dev/vality/adapter/common/exception/SecretPathNotFoundException.java
> +public class SecretPathNotFoundException extends Exception {
Хотя да.

2022-11-02 10:07 UTC, inallyoung commented
>а почему passworf 
опечатка

2022-11-02 10:11 UTC, strug approved these changes

2022-11-02 10:18 UTC, merged